# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dfsha_pb2 as dfsha__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dfsha_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DFSServiceStub:
    """Servicio DFSha - Hito 1: version monolitica C/S (un solo nodo servidor)
    Cubre RF1 (gestion del sistema de archivos) y RF2 (transferencia de archivos)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ls = channel.unary_unary(
                '/dfsha.DFSService/Ls',
                request_serializer=dfsha__pb2.LsRequest.SerializeToString,
                response_deserializer=dfsha__pb2.LsResponse.FromString,
                _registered_method=True)
        self.Mkdir = channel.unary_unary(
                '/dfsha.DFSService/Mkdir',
                request_serializer=dfsha__pb2.PathRequest.SerializeToString,
                response_deserializer=dfsha__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Rmdir = channel.unary_unary(
                '/dfsha.DFSService/Rmdir',
                request_serializer=dfsha__pb2.PathRequest.SerializeToString,
                response_deserializer=dfsha__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Rm = channel.unary_unary(
                '/dfsha.DFSService/Rm',
                request_serializer=dfsha__pb2.PathRequest.SerializeToString,
                response_deserializer=dfsha__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Send = channel.stream_unary(
                '/dfsha.DFSService/Send',
                request_serializer=dfsha__pb2.FileChunk.SerializeToString,
                response_deserializer=dfsha__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Receive = channel.unary_stream(
                '/dfsha.DFSService/Receive',
                request_serializer=dfsha__pb2.PathRequest.SerializeToString,
                response_deserializer=dfsha__pb2.FileChunk.FromString,
                _registered_method=True)


class DFSServiceServicer:
    """Servicio DFSha - Hito 1: version monolitica C/S (un solo nodo servidor)
    Cubre RF1 (gestion del sistema de archivos) y RF2 (transferencia de archivos)
    """

    def Ls(self, request, context):
        """RF1: Gestion del sistema de archivos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mkdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rmdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request_iterator, context):
        """RF2: Transferencia de archivos
        Send: el cliente sube un archivo mandando un stream de chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Receive(self, request, context):
        """Receive: el servidor envia el archivo pedido como un stream de chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DFSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ls': grpc.unary_unary_rpc_method_handler(
                    servicer.Ls,
                    request_deserializer=dfsha__pb2.LsRequest.FromString,
                    response_serializer=dfsha__pb2.LsResponse.SerializeToString,
            ),
            'Mkdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Mkdir,
                    request_deserializer=dfsha__pb2.PathRequest.FromString,
                    response_serializer=dfsha__pb2.StatusResponse.SerializeToString,
            ),
            'Rmdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Rmdir,
                    request_deserializer=dfsha__pb2.PathRequest.FromString,
                    response_serializer=dfsha__pb2.StatusResponse.SerializeToString,
            ),
            'Rm': grpc.unary_unary_rpc_method_handler(
                    servicer.Rm,
                    request_deserializer=dfsha__pb2.PathRequest.FromString,
                    response_serializer=dfsha__pb2.StatusResponse.SerializeToString,
            ),
            'Send': grpc.stream_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=dfsha__pb2.FileChunk.FromString,
                    response_serializer=dfsha__pb2.StatusResponse.SerializeToString,
            ),
            'Receive': grpc.unary_stream_rpc_method_handler(
                    servicer.Receive,
                    request_deserializer=dfsha__pb2.PathRequest.FromString,
                    response_serializer=dfsha__pb2.FileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.DFSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.DFSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DFSService:
    """Servicio DFSha - Hito 1: version monolitica C/S (un solo nodo servidor)
    Cubre RF1 (gestion del sistema de archivos) y RF2 (transferencia de archivos)
    """

    @staticmethod
    def Ls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.DFSService/Ls',
            dfsha__pb2.LsRequest.SerializeToString,
            dfsha__pb2.LsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mkdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.DFSService/Mkdir',
            dfsha__pb2.PathRequest.SerializeToString,
            dfsha__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rmdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.DFSService/Rmdir',
            dfsha__pb2.PathRequest.SerializeToString,
            dfsha__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.DFSService/Rm',
            dfsha__pb2.PathRequest.SerializeToString,
            dfsha__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Send(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dfsha.DFSService/Send',
            dfsha__pb2.FileChunk.SerializeToString,
            dfsha__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Receive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfsha.DFSService/Receive',
            dfsha__pb2.PathRequest.SerializeToString,
            dfsha__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
