# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dfsha.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dfsha.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64\x66sha.proto\x12\x05\x64\x66sha\"\x19\n\tLsRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"<\n\x08\x44irEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06is_dir\x18\x02 \x01(\x08\x12\x12\n\nsize_bytes\x18\x03 \x01(\x03\"K\n\nLsResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12 \n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x0f.dfsha.DirEntry\"\x1b\n\x0bPathRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"-\n\x0eStatusResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\'\n\tFileChunk\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x32\xb6\x02\n\nDFSService\x12)\n\x02Ls\x12\x10.dfsha.LsRequest\x1a\x11.dfsha.LsResponse\x12\x32\n\x05Mkdir\x12\x12.dfsha.PathRequest\x1a\x15.dfsha.StatusResponse\x12\x32\n\x05Rmdir\x12\x12.dfsha.PathRequest\x1a\x15.dfsha.StatusResponse\x12/\n\x02Rm\x12\x12.dfsha.PathRequest\x1a\x15.dfsha.StatusResponse\x12\x31\n\x04Send\x12\x10.dfsha.FileChunk\x1a\x15.dfsha.StatusResponse(\x01\x12\x31\n\x07Receive\x12\x12.dfsha.PathRequest\x1a\x10.dfsha.FileChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfsha_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LSREQUEST']._serialized_start=22
  _globals['_LSREQUEST']._serialized_end=47
  _globals['_DIRENTRY']._serialized_start=49
  _globals['_DIRENTRY']._serialized_end=109
  _globals['_LSRESPONSE']._serialized_start=111
  _globals['_LSRESPONSE']._serialized_end=186
  _globals['_PATHREQUEST']._serialized_start=188
  _globals['_PATHREQUEST']._serialized_end=215
  _globals['_STATUSRESPONSE']._serialized_start=217
  _globals['_STATUSRESPONSE']._serialized_end=262
  _globals['_FILECHUNK']._serialized_start=264
  _globals['_FILECHUNK']._serialized_end=303
  _globals['_DFSSERVICE']._serialized_start=306
  _globals['_DFSSERVICE']._serialized_end=616
# @@protoc_insertion_point(module_scope)
