FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dfsha_pb2.py dfsha_pb2_grpc.py server.py ./

# Carpeta donde se almacenan los archivos del DFS (se puede montar como volumen)
ENV DFSHA_ROOT=/data
RUN mkdir -p /data
VOLUME ["/data"]

EXPOSE 50051

CMD ["python", "server.py"]
